export type {
  CanonicalCommandReceipt,
  CanonicalEventId,
  CanonicalEventOrdinal,
  CanonicalJsonValue,
  CanonicalProjectActivationDiagnosticCode,
  CanonicalProjectActivationRequest,
  CanonicalProjectActivationResult,
  CanonicalProjectCommandDiagnosticCode,
  CanonicalProjectCommandRequest,
  CanonicalProjectCommandResult,
  CanonicalProjectSwitchRequest,
  CanonicalProjectSwitchResult,
  CommandId,
  CommandReceiptId,
  CommandRejection,
  ProjectActivationId,
  ProjectSequence,
  TypedCommand,
  WriterGeneration,
} from "./canonical-project-protocol.js";
export {
  CanonicalCommandReceiptSchema,
  CanonicalEventIdSchema,
  CanonicalEventOrdinalSchema,
  CanonicalJsonValueSchema,
  CanonicalProjectActivationDiagnosticCodeSchema,
  CanonicalProjectActivationRequestSchema,
  CanonicalProjectActivationResultSchema,
  CanonicalProjectCommandDiagnosticCodeSchema,
  CanonicalProjectCommandRequestSchema,
  CanonicalProjectCommandResultSchema,
  CanonicalProjectSwitchRequestSchema,
  CanonicalProjectSwitchResultSchema,
  CanonicalSettlementTimeSchema,
  CommandIdSchema,
  CommandReceiptIdSchema,
  CommandReceiptMetadataSchema,
  CommandRejectionCodeSchema,
  CommandRejectionSchema,
  ProjectActivationIdSchema,
  ProjectSequenceSchema,
  SystemCommandRejectionCodeSchema,
  TypedCommandSchema,
  WriterGenerationSchema,
} from "./canonical-project-protocol.js";
export type {
  WriterProofControl,
  WriterProofEvent,
  WriterProofStart,
} from "./canonical-writer-smoke-protocol.js";
export {
  WriterProofControlSchema,
  WriterProofEventSchema,
  WriterProofNativeMetadataSchema,
  WriterProofNativeTargetSchema,
  WriterProofStartSchema,
  writerProofFirstCommand,
  writerProofInactiveActivationId,
  writerProofNativeBindingFilename,
  writerProofNativePackageVersion,
  writerProofNextCommand,
  writerProofProjectId,
  writerProofStaleCommand,
  writerProofStaleCreateRequestId,
  writerProofStaleProjectId,
} from "./canonical-writer-smoke-protocol.js";
export type { ProjectList, ProjectListResult } from "./project-list-protocol.js";
export {
  ProjectListEntrySchema,
  ProjectListLocationSchema,
  ProjectListRequestSchema,
  ProjectListResultSchema,
  ProjectListSchema,
  ProjectListStorageSchema,
  RegistrationIdempotencyConflictSchema,
  RegistryPendingRecoverySchema,
} from "./project-list-protocol.js";
export type {
  InitialRepositoryBinding,
  RegisteredProject,
  RegisteredProjectSelectionCode,
} from "./project-registration-protocol.js";
export {
  InitialRepositoryBindingSchema,
  RegisteredProjectSchema,
  RegisteredProjectSelectionCodeSchema,
  registeredProjectSelectionCodes,
} from "./project-registration-protocol.js";
export type {
  CanonicalDatabaseLineageId,
  OpenedStorageIdentity,
  PersistenceHealth,
  ProjectDatabaseHealth,
  ProjectStorageCloseRequest,
  ProjectStorageCloseResult,
  ProjectStorageCreateRequest,
  ProjectStorageCreateRequestId,
  ProjectStorageCreateResult,
  ProjectStorageDiagnostic,
  ProjectStorageDiagnosticCode,
  ProjectStorageOpenRequest,
  ProjectStorageOpenResult,
  RuntimeDatabaseLineageId,
  StorageGenerationId,
  StorageId,
} from "./project-storage-protocol.js";
export {
  CanonicalDatabaseLineageIdSchema,
  PersistenceHealthSchema,
  ProjectDatabaseHealthSchema,
  ProjectStorageCloseRequestSchema,
  ProjectStorageCloseResultSchema,
  ProjectStorageCreateRequestIdSchema,
  ProjectStorageCreateRequestSchema,
  ProjectStorageCreateResultSchema,
  ProjectStorageDiagnosticCodeSchema,
  ProjectStorageDiagnosticSchema,
  ProjectStorageOpenRequestSchema,
  ProjectStorageOpenResultSchema,
  RuntimeDatabaseLineageIdSchema,
  StorageGenerationIdSchema,
  StorageIdSchema,
} from "./project-storage-protocol.js";
export type {
  DesktopMessage,
  HarnessBootstrap,
  HarnessFailureCode,
  HarnessMessage,
  HarnessStatus,
  MessageId,
  ProtocolParseResult,
  RetryHarnessResult,
} from "./protocol.js";
export {
  createHandshakeCommand,
  createProjectActivateCommand,
  createProjectActivateResultEvent,
  createProjectCloseCommand,
  createProjectCloseResultEvent,
  createProjectCommand,
  createProjectCommandResultEvent,
  createProjectCreateCommand,
  createProjectCreateResultEvent,
  createProjectListCommand,
  createProjectListResultEvent,
  createProjectOpenCommand,
  createProjectOpenResultEvent,
  createProjectSwitchCommand,
  createProjectSwitchResultEvent,
  createReadyEvent,
  createRequestFailureEvent,
  createSystemFailureEvent,
  createWorkspaceIntentCommand,
  createWorkspaceIntentResultEvent,
  createWorkspaceProjectionInvalidatedEvent,
  createWorkspaceQueryCommand,
  createWorkspaceQueryResultEvent,
  DesktopMessageSchema,
  HarnessBootstrapSchema,
  HarnessDiagnosticCodeSchema,
  HarnessFailureCodeSchema,
  HarnessMessageSchema,
  HarnessStatusSchema,
  MessageIdSchema,
  parseDesktopMessage,
  parseHarnessMessage,
  protocolVersion,
  RetryHarnessResultSchema,
  readMessageId,
} from "./protocol.js";
export type { SchemaIssueSummary } from "./schema-codec.js";
export {
  acceptsStrict,
  dateTimeTextSchema,
  decodeStrict,
  decodeStrictResult,
  EmptyObjectSchema,
  frozenOutput,
  NonBlankTextSchema,
  NonEmptyTextSchema,
  strictParseOptions,
  summarizeSchemaError,
  TrimmedNonEmptyTextSchema,
  UuidTextSchema,
} from "./schema-codec.js";
export type {
  AcceptedRevisionId,
  ContextProposalId,
  ContextRecordId,
  ContextRecordProjection,
  ConversationBranchId,
  ConversationId,
  ConversationMessageId,
  ConversationProjection,
  FrameDraftId,
  FrameReviewProjection,
  FrameSectionId,
  MemoryLibraryProjection,
  MemoryProposalId,
  MemoryRevisionId,
  MemoryTopicId,
  ProjectId,
  ReviewAnnotationId,
  WaypointId,
  WorkspaceCapability,
  WorkspaceDiagnostic,
  WorkspaceIntent,
  WorkspaceIntentResult,
  WorkspaceNotification,
  WorkspaceProjection,
  WorkspaceProjectionRevision,
  WorkspaceQuery,
  WorkspaceQueryResult,
  WorkspaceScope,
} from "./workspace-protocol.js";
export {
  AcceptedRevisionIdSchema,
  ContextProposalIdSchema,
  ContextRecordIdSchema,
  ContextRecordProjectionSchema,
  ConversationBranchIdSchema,
  ConversationIdSchema,
  ConversationMessageIdSchema,
  ConversationProjectionSchema,
  FrameDraftIdSchema,
  FrameReviewProjectionSchema,
  FrameSectionIdSchema,
  MemoryLibraryProjectionSchema,
  MemoryProposalIdSchema,
  MemoryRevisionIdSchema,
  MemoryTopicIdSchema,
  ProjectIdSchema,
  ReviewAnnotationIdSchema,
  WaypointIdSchema,
  WorkspaceCapabilitySchema,
  WorkspaceDiagnosticSchema,
  WorkspaceIntentResultSchema,
  WorkspaceIntentSchema,
  WorkspaceNotificationSchema,
  WorkspaceProjectionRevisionSchema,
  WorkspaceProjectionSchema,
  WorkspaceQueryResultSchema,
  WorkspaceQuerySchema,
  WorkspaceScopeSchema,
} from "./workspace-protocol.js";
